version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - '.:/app'
      - '/app/node_modules'
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=blog_api
      - MYSQL_ROOT_PASSWORD=barasy10000
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: